spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter

        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/progres/**
          filters:
            - AuthFilter

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
          filters:
            - AuthFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Authorization

application:
  name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/